// Demo/screenshot seed data is disabled by default to keep production flows clean.
export const SCREENSHOT_MOCKS_ENABLED = false;

export const SCREENSHOT_FEED_POSTS = [
    {
        _id: 'feed-post-1',
        type: 'text',
        author: 'Rajesh Kumar',
        authorId: 'u1',
        role: 'Job Seeker',
        time: '2h ago',
        text: 'Looking for delivery partner work in Gachibowli. Ready to start this week.',
        likes: 18,
        comments: 2,
        vouchCount: 3,
        commentEntries: [
            { id: 'c1', text: 'We are hiring in Secunderabad too.', author: 'Sarah Jenkins', time: '1h ago' },
            { id: 'c2', text: 'DM sent!', author: 'Aditi Sharma', time: '45m ago' },
        ],
        avatar: 'https://ui-avatars.com/api/?name=Rajesh+Kumar&background=d1d5db&color=111111&rounded=true',
        visibility: 'community',
        postType: 'status',
    },
    {
        _id: 'feed-post-2',
        type: 'gallery',
        author: 'Sarah Jenkins',
        authorId: 'u2',
        role: 'Employer',
        time: '5h ago',
        text: 'Hiring warehouse supervisors in Secunderabad. Night shift available.',
        likes: 32,
        comments: 4,
        vouchCount: 6,
        images: [
            'https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1200&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1200&auto=format&fit=crop',
        ],
        avatar: 'https://ui-avatars.com/api/?name=Sarah+Jenkins&background=8b3dff&color=fff&rounded=true',
        visibility: 'public',
        postType: 'status',
    },
    {
        _id: 'feed-post-3',
        type: 'bounty',
        author: 'Hireapp Community',
        authorId: 'u3',
        role: 'Community',
        time: '1d ago',
        text: 'Refer a heavy vehicle driver and earn a referral bonus.',
        likes: 14,
        comments: 1,
        vouchCount: 2,
        reward: '₹5,000',
        avatar: 'https://ui-avatars.com/api/?name=Hireapp+Community&background=8b3dff&color=fff&rounded=true',
        visibility: 'community',
        postType: 'bounty',
    },
    {
        _id: 'feed-post-4',
        type: 'text',
        author: 'Aditi Sharma',
        authorId: 'u4',
        role: 'Employer',
        time: '3h ago',
        text: 'We have 6 open delivery slots in Secunderabad this week. DM for shift details.',
        likes: 22,
        comments: 3,
        vouchCount: 4,
        commentEntries: [
            { id: 'c4-1', text: 'Sent you a message.', author: 'Harish Verma', time: '2h ago' },
            { id: 'c4-2', text: 'Any night shift?', author: 'Meera Nair', time: '1h ago' },
        ],
        avatar: 'https://ui-avatars.com/api/?name=Aditi+Sharma&background=8b3dff&color=fff&rounded=true',
        visibility: 'public',
        postType: 'status',
    },
    {
        _id: 'feed-post-5',
        type: 'gallery',
        author: 'Meera Nair',
        authorId: 'u5',
        role: 'Job Seeker',
        time: '6h ago',
        text: 'Finished a safety training workshop today. Ready for warehouse roles.',
        likes: 19,
        comments: 2,
        vouchCount: 1,
        images: [
            'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1545239351-ef35f43d514b?q=80&w=1200&auto=format&fit=crop',
        ],
        avatar: 'https://ui-avatars.com/api/?name=Meera+Nair&background=d1d5db&color=111111&rounded=true',
        visibility: 'community',
        postType: 'status',
    },
    {
        _id: 'feed-post-6',
        type: 'text',
        author: 'Vikram Rao',
        authorId: 'u6',
        role: 'Mentor',
        time: '9h ago',
        text: 'Pro tip: If you are on night shift, hydrate early and keep meal breaks consistent.',
        likes: 40,
        comments: 6,
        vouchCount: 8,
        commentEntries: [
            { id: 'c6-1', text: 'This helped me a lot last week.', author: 'Kavya Iyer', time: '7h ago' },
        ],
        avatar: 'https://ui-avatars.com/api/?name=Vikram+Rao&background=8b3dff&color=fff&rounded=true',
        visibility: 'public',
        postType: 'status',
    },
    {
        _id: 'feed-post-7',
        type: 'bounty',
        author: 'RapidLogistics',
        authorId: 'u7',
        role: 'Employer',
        time: '2d ago',
        text: 'Looking for a fleet supervisor referral. Bonus for verified profiles.',
        likes: 11,
        comments: 0,
        vouchCount: 1,
        reward: '₹8,000',
        avatar: 'https://ui-avatars.com/api/?name=RapidLogistics&background=8b3dff&color=fff&rounded=true',
        visibility: 'community',
        postType: 'bounty',
    },
    {
        _id: 'feed-post-8',
        type: 'text',
        author: 'Priya Sharma',
        authorId: 'u8',
        role: 'Employer',
        time: '1d ago',
        text: 'Hiring warehouse associates for morning shifts. Interview slots open this Friday.',
        likes: 27,
        comments: 4,
        vouchCount: 5,
        commentEntries: [
            { id: 'c8-1', text: 'Is there a Sunday slot?', author: 'Nikhil Singh', time: '1d ago' },
        ],
        avatar: 'https://ui-avatars.com/api/?name=Priya+Sharma&background=8b3dff&color=fff&rounded=true',
        visibility: 'public',
        postType: 'status',
    },
];

export const SCREENSHOT_FEED_LIKED_IDS = ['feed-post-1', 'feed-post-3'];
export const SCREENSHOT_FEED_SAVED_IDS = ['feed-post-2'];
export const SCREENSHOT_FEED_LIKE_MAP = {
    'feed-post-1': 18,
    'feed-post-2': 32,
    'feed-post-3': 14,
    'feed-post-4': 22,
    'feed-post-5': 19,
    'feed-post-6': 40,
    'feed-post-7': 11,
    'feed-post-8': 27,
};

export const SCREENSHOT_PULSE_ITEMS = [
    {
        id: 'pulse-1',
        jobId: 'zip-j1',
        title: 'Heavy Vehicle Driver',
        employer: 'LogiTech Solutions',
        companyName: 'LogiTech Solutions',
        distance: '3.2 km',
        location: 'Hyderabad',
        pay: '₹25,000 - ₹30,000',
        urgent: true,
        timePosted: '2h ago',
        postType: 'job',
        requirements: ['Heavy License', 'Night Shift', 'Route Knowledge'],
        description: 'Inter-city logistics hiring for experienced drivers.',
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'pulse-2',
        jobId: 'zip-j2',
        title: 'Warehouse Supervisor',
        employer: 'Amazon Delivers',
        companyName: 'Amazon Delivers',
        distance: '5.8 km',
        location: 'Secunderabad',
        pay: '₹35,000',
        urgent: false,
        timePosted: '1d ago',
        postType: 'job',
        requirements: ['Team Management', 'Inventory', 'Excel'],
        description: 'Supervise dock staff and manage inbound inventory.',
        createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'pulse-3',
        jobId: 'zip-j3',
        title: 'Delivery Partner',
        employer: 'Swiggy',
        companyName: 'Swiggy',
        distance: '2.4 km',
        location: 'Gachibowli',
        pay: '₹18,000 + Incentives',
        urgent: true,
        timePosted: '4h ago',
        postType: 'job',
        requirements: ['Two Wheeler', 'Smartphone'],
        description: 'Flexible shifts with weekly incentives.',
        createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    },
];

export const SCREENSHOT_PULSE_APPLIED_IDS = ['pulse-1'];

export const SCREENSHOT_PULSE_NEARBY_PROS = [
    {
        id: 'pro-1',
        name: 'Aditi Sharma',
        role: 'Warehouse Supervisor',
        distance: '2.1 km',
        karma: '420',
        available: true,
        avatar: 'https://ui-avatars.com/api/?name=Aditi+Sharma&background=8b3dff&color=fff&rounded=true',
    },
    {
        id: 'pro-2',
        name: 'Harish Verma',
        role: 'Delivery Lead',
        distance: '4.4 km',
        karma: '310',
        available: false,
        avatar: 'https://ui-avatars.com/api/?name=Harish+Verma&background=8b3dff&color=fff&rounded=true',
    },
    {
        id: 'pro-3',
        name: 'Meera Nair',
        role: 'Fleet Manager',
        distance: '6.0 km',
        karma: '512',
        available: true,
        avatar: 'https://ui-avatars.com/api/?name=Meera+Nair&background=8b3dff&color=fff&rounded=true',
    },
];

export const SCREENSHOT_ACADEMY_COURSES = [
    {
        id: 'course-1',
        title: 'Warehouse Safety Essentials',
        instructor: 'Hireapp Academy',
        duration: '2h 15m',
        level: 'Beginner',
        enrolledCount: 1240,
        lessonCount: 8,
        thumbnailUrl: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?q=80&w=1200&auto=format&fit=crop',
    },
    {
        id: 'course-2',
        title: 'Route Planning Mastery',
        instructor: 'Logistics Pro',
        duration: '1h 40m',
        level: 'Intermediate',
        enrolledCount: 640,
        lessonCount: 6,
        thumbnailUrl: 'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?q=80&w=1200&auto=format&fit=crop',
    },
    {
        id: 'course-3',
        title: 'Customer Service for Delivery',
        instructor: 'Hireapp Academy',
        duration: '1h 10m',
        level: 'Beginner',
        enrolledCount: 860,
        lessonCount: 5,
        thumbnailUrl: 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?q=80&w=1200&auto=format&fit=crop',
    },
];

export const SCREENSHOT_ACADEMY_ENROLLED = [
    { courseId: 'course-1', startedAt: new Date().toISOString(), progressPercent: 38 },
];

export const SCREENSHOT_ACADEMY_MENTORS = [
    {
        id: 'mentor-1',
        name: 'Vikram Rao',
        exp: '8y',
        skill: 'Logistics Ops',
        rating: '4.9',
        sessions: '240',
        reason: 'Matched to your delivery profile',
        avatar: 'https://ui-avatars.com/api/?name=Vikram+Rao&background=8b3dff&color=fff&rounded=true',
    },
    {
        id: 'mentor-2',
        name: 'Neha Patel',
        exp: '6y',
        skill: 'Warehouse Lead',
        rating: '4.7',
        sessions: '180',
        reason: 'Great for supervisor track',
        avatar: 'https://ui-avatars.com/api/?name=Neha+Patel&background=8b3dff&color=fff&rounded=true',
    },
];

export const SCREENSHOT_CONNECTED_MENTOR_IDS = ['mentor-2'];

export const SCREENSHOT_CIRCLES = [
    {
        _id: 'circle-1',
        name: 'Hyderabad Drivers',
        category: 'Delivery & Logistics',
        memberCount: 320,
        communityTrustScore: 78,
        description: 'Routes, payouts, and shift tips for local drivers.',
        privacy: 'public',
        topics: ['Routes', 'Fuel Tips', 'Hiring'],
        isJoined: true,
    },
    {
        _id: 'circle-2',
        name: 'Warehouse Leads',
        category: 'Operations',
        memberCount: 140,
        communityTrustScore: 64,
        description: 'Warehouse staffing, shift planning, and safety.',
        privacy: 'public',
        topics: ['Safety', 'Roster', 'Tools'],
        isJoined: false,
    },
    {
        _id: 'circle-3',
        name: 'Fleet Managers',
        category: 'Management',
        memberCount: 88,
        communityTrustScore: 71,
        description: 'Fleet ops, maintenance schedules, and cost control.',
        privacy: 'private',
        topics: ['Maintenance', 'Dispatch', 'Compliance'],
        joinRequestPending: true,
        isJoined: false,
    },
];

export const SCREENSHOT_JOINED_CIRCLE_IDS = ['circle-1'];
export const SCREENSHOT_PENDING_JOIN_IDS = ['circle-3'];

export const SCREENSHOT_CIRCLE_MESSAGES = [
    {
        id: 'msg-1',
        user: 'Aditi Sharma',
        role: 'Employer',
        text: 'Anyone available for a late-night pickup run today?',
        time: '10:12 AM',
        type: 'text',
        isAdmin: true,
    },
    {
        id: 'msg-2',
        user: 'Rajesh Kumar',
        role: 'Job Seeker',
        text: 'I can do 8pm onward. Please share the location.',
        time: '10:14 AM',
        type: 'text',
        isAdmin: false,
    },
];

export const SCREENSHOT_CIRCLE_MEMBERS = [
    { id: 'member-1', name: 'Aditi Sharma', role: 'Employer', isAdmin: true },
    { id: 'member-2', name: 'Rajesh Kumar', role: 'Driver', isAdmin: false },
    { id: 'member-3', name: 'Meera Nair', role: 'Fleet Ops', isAdmin: false },
];

export const SCREENSHOT_CIRCLE_RATES = [
    { service: 'Route Driver', price: '₹900/day' },
    { service: 'Night Shift', price: '₹1,200/day' },
];

export const SCREENSHOT_BOUNTIES = [
    {
        id: 'bounty-1',
        company: 'LogiTech Solutions',
        logoLetter: 'L',
        logoBg: '#7c3aed',
        role: 'Urgent Driver Referral',
        description: 'Refer a heavy vehicle driver for inter-city runs.',
        bonus: '₹5,000',
        bonusValue: 5000,
        status: 'open',
        expiresInDays: 6,
        totalPot: '₹15,000',
        referrals: 3,
        category: 'OPEN',
        hasSubmitted: false,
        isCreator: false,
        isWinner: false,
    },
    {
        id: 'bounty-2',
        company: 'Amazon Delivers',
        logoLetter: 'A',
        logoBg: '#7c3aed',
        role: 'Warehouse Supervisor',
        description: 'Looking for a supervisor with inventory experience.',
        bonus: '₹8,000',
        bonusValue: 8000,
        status: 'reviewing',
        expiresInDays: 2,
        totalPot: '₹24,000',
        referrals: 4,
        category: 'REVIEWING',
        hasSubmitted: true,
        isCreator: false,
        isWinner: false,
    },
];

export const SCREENSHOT_BOUNTY_REFERRED_IDS = ['bounty-2'];
export const SCREENSHOT_BOUNTY_STATS = { totalEarnings: 8000 };

export const SCREENSHOT_APPLICATIONS_RAW = [
    {
        _id: 'app-1',
        status: 'interview_requested',
        lastMessage: 'Great, see you tomorrow at 10 AM.',
        updatedAt: new Date().toISOString(),
        job: { title: 'Heavy Vehicle Driver', companyName: 'LogiTech Solutions' },
        employer: { companyName: 'LogiTech Solutions', name: 'Sarah Jenkins' },
        worker: { firstName: 'Rajesh', lastName: 'Kumar', roleProfiles: [{ roleName: 'Driver' }] },
    },
    {
        _id: 'app-2',
        status: 'shortlisted',
        lastMessage: 'Your profile looks good. We will confirm soon.',
        updatedAt: new Date(Date.now() - 86400000).toISOString(),
        job: { title: 'Delivery Partner', companyName: 'Swiggy' },
        employer: { companyName: 'Swiggy', name: 'Hiring Team' },
        worker: { firstName: 'Rajesh', lastName: 'Kumar', roleProfiles: [{ roleName: 'Delivery Partner' }] },
    },
    {
        _id: 'app-3',
        status: 'hired',
        lastMessage: 'Welcome aboard! Your start date is Monday.',
        updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
        job: { title: 'Warehouse Supervisor', companyName: 'Amazon Delivers' },
        employer: { companyName: 'Amazon Delivers', name: 'Recruiter' },
        worker: { firstName: 'Rajesh', lastName: 'Kumar', roleProfiles: [{ roleName: 'Supervisor' }] },
    },
    {
        _id: 'app-4',
        status: 'applied',
        lastMessage: 'Application sent successfully.',
        updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
        job: { title: 'Fleet Coordinator', companyName: 'RapidLogistics' },
        employer: { companyName: 'RapidLogistics', name: 'Hiring Desk' },
        worker: { firstName: 'Rajesh', lastName: 'Kumar', roleProfiles: [{ roleName: 'Fleet Coordinator' }] },
    },
    {
        _id: 'app-5',
        status: 'interview_completed',
        lastMessage: 'Thanks for completing the interview. We will update you soon.',
        updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
        job: { title: 'Route Planner', companyName: 'City Freight' },
        employer: { companyName: 'City Freight', name: 'Talent Team' },
        worker: { firstName: 'Rajesh', lastName: 'Kumar', roleProfiles: [{ roleName: 'Route Planner' }] },
    },
    {
        _id: 'app-6',
        status: 'offer_sent',
        lastMessage: 'Offer sent. Please confirm by EOD.',
        updatedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
        job: { title: 'Warehouse Executive', companyName: 'LogiTech Solutions' },
        employer: { companyName: 'LogiTech Solutions', name: 'Hiring Desk' },
        worker: { firstName: 'Aditi', lastName: 'Sharma', roleProfiles: [{ roleName: 'Warehouse Executive' }] },
    },
    {
        _id: 'app-7',
        status: 'shortlisted',
        lastMessage: 'Shortlisted. Schedule interview?',
        updatedAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
        job: { title: 'Fleet Coordinator', companyName: 'RapidLogistics' },
        employer: { companyName: 'RapidLogistics', name: 'Recruiter' },
        worker: { firstName: 'Harish', lastName: 'Verma', roleProfiles: [{ roleName: 'Fleet Coordinator' }] },
    },
    {
        _id: 'app-8',
        status: 'interview_requested',
        lastMessage: 'Interview scheduled for tomorrow at 11 AM.',
        updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
        job: { title: 'Warehouse Associate', companyName: 'Metro Warehousing' },
        employer: { companyName: 'Metro Warehousing', name: 'Priya Sharma' },
        worker: { firstName: 'Meera', lastName: 'Nair', roleProfiles: [{ roleName: 'Warehouse Associate' }] },
    },
    {
        _id: 'app-9',
        status: 'offer_accepted',
        lastMessage: 'Offer accepted. Joining confirmation sent.',
        updatedAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
        job: { title: 'Delivery Executive', companyName: 'City Freight' },
        employer: { companyName: 'City Freight', name: 'Talent Desk' },
        worker: { firstName: 'Arjun', lastName: 'Rao', roleProfiles: [{ roleName: 'Delivery Executive' }] },
    },
    {
        _id: 'app-10',
        status: 'applied',
        lastMessage: 'New application received.',
        updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        job: { title: 'Logistics Associate', companyName: 'SwiftCargo' },
        employer: { companyName: 'SwiftCargo', name: 'Hiring Manager' },
        worker: { firstName: 'Nikhil', lastName: 'Singh', roleProfiles: [{ roleName: 'Logistics Associate' }] },
    },
    {
        _id: 'app-11',
        status: 'shortlisted',
        lastMessage: 'Shortlisted for next round.',
        updatedAt: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
        job: { title: 'Inventory Analyst', companyName: 'Stockwise' },
        employer: { companyName: 'Stockwise', name: 'Recruiter' },
        worker: { firstName: 'Kavya', lastName: 'Iyer', roleProfiles: [{ roleName: 'Inventory Analyst' }] },
    },
    {
        _id: 'app-12',
        status: 'hired',
        lastMessage: 'Congrats! Start date confirmed.',
        updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        job: { title: 'Fleet Supervisor', companyName: 'RapidLogistics' },
        employer: { companyName: 'RapidLogistics', name: 'HR Team' },
        worker: { firstName: 'Suresh', lastName: 'Patel', roleProfiles: [{ roleName: 'Fleet Supervisor' }] },
    },
];

export const SCREENSHOT_NOTIFICATIONS = [
    {
        _id: 'notif-1',
        type: 'match_found',
        title: 'New match in your area',
        message: 'A heavy driver role matches your profile near Hyderabad.',
        createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
        isRead: false,
        relatedData: {},
    },
    {
        _id: 'notif-2',
        type: 'application_received',
        title: 'Application update',
        message: 'Your delivery partner application was shortlisted.',
        createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        isRead: false,
        relatedData: { jobId: 'zip-j3' },
    },
    {
        _id: 'notif-3',
        type: 'message_received',
        title: 'Message from recruiter',
        message: 'Can you share your availability for next week?',
        createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
        isRead: true,
        relatedData: { applicationId: 'app-1' },
    },
];

export const SCREENSHOT_PROFILES = [
    {
        _id: 'profile-1',
        profileId: 'profile-1',
        name: 'Rajesh Kumar',
        roleTitle: 'Heavy Driver',
        experienceYears: 10,
        expectedSalary: 28000,
        skills: ['Heavy License', 'Highway Driving', 'Route Optimization', 'Basic Mechanics'],
        location: 'Hyderabad',
        panchayat: 'Gachibowli',
        language: 'Telugu',
        maxCommuteDistanceKm: 25,
        minimumMatchTier: 'GOOD',
        preferredShift: 'Day',
        isAvailable: true,
        availabilityWindowDays: 0,
        openToRelocation: false,
        openToNightShift: true,
        licenses: ['HMV License', 'First Aid'],
        avatar: 'https://ui-avatars.com/api/?name=Rajesh+Kumar&background=8b3dff&color=fff&rounded=true',
        interviewVerified: true,
        activeProfile: true,
        isDefault: true,
        createdAt: new Date().toISOString(),
    },
    {
        _id: 'profile-2',
        profileId: 'profile-2',
        name: 'Rajesh Kumar',
        roleTitle: 'Private Chauffeur',
        experienceYears: 4,
        expectedSalary: 22000,
        skills: ['Client Relations', 'Automatic Transmission', 'Navigation'],
        location: 'Hyderabad',
        panchayat: 'Jubilee Hills',
        language: 'English',
        maxCommuteDistanceKm: 10,
        minimumMatchTier: 'POSSIBLE',
        preferredShift: 'Flexible',
        isAvailable: true,
        availabilityWindowDays: 15,
        openToRelocation: false,
        openToNightShift: false,
        licenses: ['LMV License'],
        avatar: 'https://ui-avatars.com/api/?name=Rajesh+Kumar&background=8b3dff&color=fff&rounded=true',
        interviewVerified: false,
        activeProfile: false,
        isDefault: false,
        createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
];

export const SCREENSHOT_TALENT_POOLS = [
    { id: 'pool-1', name: 'Heavy Vehicle Driver', count: 14, tags: ['Night Shift'] },
    { id: 'pool-2', name: 'Warehouse Supervisor', count: 6, tags: ['Inventory'] },
];

export const SCREENSHOT_TALENT_CANDIDATES = {
    'pool-1': [
        {
            id: 'candidate-1',
            userId: 'u1',
            workerProfileId: 'wp-1',
            avatar: 'https://ui-avatars.com/api/?name=Aditi+Sharma&background=8b3dff&color=fff&rounded=true',
            name: 'Aditi Sharma',
            roleTitle: 'Heavy Driver',
            summary: '6 years experience on inter-city routes. Interview verified.',
            experienceYears: 6,
            skills: ['Heavy License', 'Route Knowledge', 'Night Shift'],
            qualifications: ['HMV License'],
            location: 'Hyderabad',
            matchScore: 92,
            profilePercentile: 88,
            applicationId: 'app-1',
            statusRaw: 'shortlisted',
            statusLabel: 'Shortlisted',
            interviewVerified: true,
            communicationClarityTag: 'Clear communicator',
            profileStrengthLabel: 'Strong profile',
            salaryAlignmentStatus: 'ALIGNED',
            verifiedPriorityActive: true,
            resumeUrl: null,
            transcript: '',
            whyMatch: 'Available immediately and matches night shift requirement.',
            explainability: {},
            topReasons: ['Route knowledge', 'Night shift ready'],
            confidenceScore: 0.86,
            timelineTransparency: null,
            matchScoreSource: 'mock',
            matchModelVersionUsed: null,
            probabilisticFallbackUsed: false,
        },
        {
            id: 'candidate-2',
            userId: 'u2',
            workerProfileId: 'wp-2',
            avatar: 'https://ui-avatars.com/api/?name=Harish+Verma&background=8b3dff&color=fff&rounded=true',
            name: 'Harish Verma',
            roleTitle: 'Delivery Lead',
            summary: '5 years in last-mile delivery. Strong customer ratings.',
            experienceYears: 5,
            skills: ['Two Wheeler', 'Customer Service'],
            qualifications: ['LMV License'],
            location: 'Gachibowli',
            matchScore: 84,
            profilePercentile: 72,
            applicationId: 'app-2',
            statusRaw: 'interview_requested',
            statusLabel: 'Interview requested',
            interviewVerified: false,
            communicationClarityTag: 'Clear communicator',
            profileStrengthLabel: 'Growing profile',
            salaryAlignmentStatus: 'ALIGNED',
            verifiedPriorityActive: false,
            resumeUrl: null,
            transcript: '',
            whyMatch: 'Flexible schedule with strong delivery record.',
            explainability: {},
            topReasons: ['Delivery experience', 'Flexible shift'],
            confidenceScore: 0.74,
            timelineTransparency: null,
            matchScoreSource: 'mock',
            matchModelVersionUsed: null,
            probabilisticFallbackUsed: false,
        },
    ],
    'pool-2': [
        {
            id: 'candidate-3',
            userId: 'u3',
            workerProfileId: 'wp-3',
            avatar: 'https://ui-avatars.com/api/?name=Meera+Nair&background=8b3dff&color=fff&rounded=true',
            name: 'Meera Nair',
            roleTitle: 'Warehouse Supervisor',
            summary: '4 years managing inventory and shift staffing.',
            experienceYears: 4,
            skills: ['Inventory', 'Team Leadership', 'Excel'],
            qualifications: ['BBA'],
            location: 'Secunderabad',
            matchScore: 89,
            profilePercentile: 81,
            applicationId: 'app-3',
            statusRaw: 'hired',
            statusLabel: 'Hired',
            interviewVerified: true,
            communicationClarityTag: 'Clear communicator',
            profileStrengthLabel: 'Strong profile',
            salaryAlignmentStatus: 'ALIGNED',
            verifiedPriorityActive: true,
            resumeUrl: null,
            transcript: '',
            whyMatch: 'Experience supervising teams and inventory.',
            explainability: {},
            topReasons: ['Leadership', 'Inventory skills'],
            confidenceScore: 0.82,
            timelineTransparency: null,
            matchScoreSource: 'mock',
            matchModelVersionUsed: null,
            probabilisticFallbackUsed: false,
        },
    ],
};

export const SCREENSHOT_EMPLOYER_JOBS = [
    {
        id: 'emp-job-1',
        title: 'Heavy Vehicle Driver',
        company: 'LogiTech Solutions',
        location: 'Hyderabad',
        salary: '₹25,000 - ₹30,000',
        type: 'Full-time',
        postedAt: '2d ago',
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        description: 'Inter-city logistics hiring for experienced drivers.',
        skills: ['Heavy License', 'Night Shift', 'Route Knowledge'],
        applicantCount: 12,
        shortlistedCount: 4,
        hiredCount: 1,
        acceptedCount: 1,
        status: 'open',
    },
    {
        id: 'emp-job-2',
        title: 'Warehouse Supervisor',
        company: 'Amazon Delivers',
        location: 'Secunderabad',
        salary: '₹35,000',
        type: 'Full-time',
        postedAt: '5d ago',
        createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        description: 'Supervise dock staff and manage inbound inventory.',
        skills: ['Team Management', 'Inventory', 'Excel'],
        applicantCount: 8,
        shortlistedCount: 3,
        hiredCount: 0,
        acceptedCount: 0,
        status: 'paused',
    },
    {
        id: 'emp-job-3',
        title: 'Delivery Partner',
        company: 'Swiggy',
        location: 'Gachibowli',
        salary: '₹18,000 + Incentives',
        type: 'Part-time',
        postedAt: '1w ago',
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        description: 'Bike delivery partners needed. Flexible shifts.',
        skills: ['Two Wheeler', 'Smartphone'],
        applicantCount: 20,
        shortlistedCount: 6,
        hiredCount: 2,
        acceptedCount: 2,
        status: 'open',
    },
];
