require('dotenv').config();

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const connectDB = require('../config/db');
const MatchModel = require('../models/MatchModel');
const MatchModelReport = require('../models/MatchModelReport');

const parseModelKey = (modelKey = '*::*') => {
    const [city = '*', roleCluster = '*'] = String(modelKey || '*::*').split('::');
    return { city, roleCluster };
};

const main = async () => {
    const backendRoot = path.join(__dirname, '..');
    const repoRoot = path.join(backendRoot, '..');

    const trainingFile = path.join(backendRoot, 'training-data', 'match-training.json');
    const artifactFile = path.join(backendRoot, 'training-data', 'match-model-artifacts.json');
    const summaryFile = path.join(backendRoot, 'training-data', 'model-training-report.json');

    const minClusterSamples = Number.parseInt(process.env.MATCH_MODEL_MIN_CLUSTER_SAMPLES || '120', 10);
    const minCitySamples = Number.parseInt(process.env.MATCH_MODEL_MIN_CITY_SAMPLES || '240', 10);
    const minPositiveSamples = Number.parseInt(process.env.MATCH_MODEL_MIN_POSITIVE_SAMPLES || '20', 10);
    const randomSeed = Number.parseInt(process.env.MATCH_TRAIN_RANDOM_SEED || '42', 10);

    if (!fs.existsSync(trainingFile)) {
        throw new Error(`Training dataset missing at ${trainingFile}. Run match:extract-training first.`);
    }

    const pythonExecutable = process.env.MATCH_TRAIN_PYTHON || 'python3';
    const trainerScript = path.join(repoRoot, 'matching-engine', 'train_logistic.py');

    const trainProcess = spawnSync(
        pythonExecutable,
        [
            trainerScript,
            '--input', trainingFile,
            '--output', artifactFile,
            '--random-seed', String(randomSeed),
            '--min-cluster-samples', String(minClusterSamples),
            '--min-city-samples', String(minCitySamples),
            '--min-positive-samples', String(minPositiveSamples),
        ],
        {
            cwd: repoRoot,
            encoding: 'utf-8',
            maxBuffer: 20 * 1024 * 1024,
        }
    );

    if (trainProcess.status !== 0) {
        throw new Error(`Python trainer failed: ${trainProcess.stderr || trainProcess.stdout}`);
    }

    if (!fs.existsSync(artifactFile)) {
        throw new Error('Training artifacts not generated by Python trainer.');
    }

    const artifact = JSON.parse(fs.readFileSync(artifactFile, 'utf-8'));

    const holdoutAuc = Number(artifact?.aggregateMetrics?.holdoutAuc || 0);
    const calibrationError = Number(artifact?.aggregateMetrics?.calibrationError || 1);
    const gatePassed = holdoutAuc >= 0.78 && calibrationError <= 0.2;

    await connectDB();

    const modelVersion = String(artifact.modelVersion || Date.now());

    await MatchModel.deleteMany({ modelVersion });

    const rowsToInsert = (artifact.models || []).map((model) => {
        const parsed = parseModelKey(model.modelKey);
        return {
            modelVersion,
            modelKey: model.modelKey,
            city: parsed.city,
            roleCluster: parsed.roleCluster,
            featureOrder: model.featureOrder || artifact.featureOrder || [],
            weights: model.weights || [],
            intercept: Number(model.intercept || 0),
            sampleCount: Number(model.sampleCount || 0),
            positiveCount: Number(model.positiveCount || 0),
            metrics: model.metrics || {},
            isActive: false,
            trainedAt: new Date(),
        };
    });

    if (rowsToInsert.length > 0) {
        await MatchModel.insertMany(rowsToInsert, { ordered: false });
    }

    if (gatePassed && rowsToInsert.length > 0) {
        await MatchModel.updateMany({ isActive: true }, { $set: { isActive: false } });
        await MatchModel.updateMany({ modelVersion }, { $set: { isActive: true } });
    }

    const reportPayload = {
        modelVersion,
        aggregateMetrics: artifact.aggregateMetrics || {},
        perClusterMetrics: artifact.perClusterMetrics || {},
        activationGate: {
            requiredHoldoutAuc: 0.78,
            requiredMaxCalibrationError: 0.2,
            actualHoldoutAuc: holdoutAuc,
            actualCalibrationError: calibrationError,
            passed: gatePassed,
        },
        activated: gatePassed && rowsToInsert.length > 0,
        status: rowsToInsert.length > 0 ? 'trained' : 'failed',
        notes: rowsToInsert.length > 0
            ? (gatePassed ? 'Model version activated.' : 'Model trained but activation gate failed.')
            : 'No trained models were produced.',
    };

    await MatchModelReport.findOneAndUpdate(
        { modelVersion },
        { $set: reportPayload },
        { upsert: true, new: true }
    );

    fs.writeFileSync(summaryFile, JSON.stringify({
        modelVersion,
        modelsStored: rowsToInsert.length,
        gatePassed,
        report: reportPayload,
        aggregateMetrics: artifact.aggregateMetrics || {},
    }, null, 2));

    console.log(JSON.stringify({
        event: 'match_model_training_completed',
        modelVersion,
        modelsStored: rowsToInsert.length,
        gatePassed,
        holdoutAuc,
        calibrationError,
    }, null, 2));

    process.exit(0);
};

main().catch((error) => {
    console.warn('[trainModel] failed:', error.message);
    process.exit(1);
});
