'use strict';
/**
 * apRegionalDataV19.js
 *
 * Andhra Pradesh regional coverage dataset for the AP-first matcher.
 * This version keeps the production-friendly "expanded launch subset in code,
 * full long-tail in DB" pattern while enriching the geography with LGD-oriented
 * metadata, Madanapalle-first village coverage, and curated district anchors
 * across the AP rollout map.
 */

const ZONE = Object.freeze({
    URBAN: 'urban',
    SEMIURBAN: 'semiurban',
    RURAL: 'rural',
    AGRICULTURAL: 'agricultural',
    COASTAL: 'coastal',
    INDUSTRIAL: 'industrial',
    CAMPUS: 'campus',
    TRIBAL: 'tribal',
});

const AP_DISTRICTS = Object.freeze([
    { lgdCode: 745, name: 'Alluri Sitharama Raju' },
    { lgdCode: 744, name: 'Anakapalli' },
    { lgdCode: 502, name: 'Ananthapuramu' },
    { lgdCode: 753, name: 'Annamayya' },
    { lgdCode: 750, name: 'Bapatla' },
    { lgdCode: 503, name: 'Chittoor' },
    { lgdCode: 747, name: 'Dr. B.R. Ambedkar Konaseema' },
    { lgdCode: 505, name: 'East Godavari' },
    { lgdCode: 748, name: 'Eluru' },
    { lgdCode: 506, name: 'Guntur' },
    { lgdCode: 746, name: 'Kakinada' },
    { lgdCode: 510, name: 'Krishna' },
    { lgdCode: 511, name: 'Kurnool' },
    { lgdCode: 790, name: 'Markapuram' },
    { lgdCode: 755, name: 'Nandyal' },
    { lgdCode: 749, name: 'NTR' },
    { lgdCode: 751, name: 'Palnadu' },
    { lgdCode: 743, name: 'Parvathipuram Manyam' },
    { lgdCode: 791, name: 'Polavaram' },
    { lgdCode: 517, name: 'Prakasam' },
    { lgdCode: 519, name: 'Srikakulam' },
    { lgdCode: 515, name: 'Sri Potti Sriramulu Nellore' },
    { lgdCode: 754, name: 'Sri Sathya Sai' },
    { lgdCode: 752, name: 'Tirupati' },
    { lgdCode: 520, name: 'Visakhapatnam' },
    { lgdCode: 521, name: 'Vizianagaram' },
    { lgdCode: 523, name: 'West Godavari' },
    { lgdCode: 504, name: 'Y.S.R. Kadapa' },
    { lgdCode: 753, name: 'Madanapalle', canonicalDistrict: 'Annamayya', isLaunchHub: true },
]);

const withCompatFields = (row) => Object.freeze({
    ...row,
    n: row.name,
});

const BASE_AP_LOCATIONS = Object.freeze([
    withCompatFields({
        name: 'Madanapalle',
        aliases: ['Madanapalli'],
        lat: 13.55,
        lng: 78.5,
        zone: ZONE.SEMIURBAN,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Madanapalle',
    }),
    withCompatFields({
        name: 'Ankisettipalle',
        lat: 13.5406,
        lng: 78.4853,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Ankisettipalle',
    }),
    withCompatFields({
        name: 'Basinikonda',
        lat: 13.5497,
        lng: 78.5004,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Basinikonda',
    }),
    withCompatFields({
        name: 'Chinnathippasamudram',
        lat: 13.524,
        lng: 78.481,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Chinnathippasamudram',
    }),
    withCompatFields({
        name: 'Chippili',
        lat: 13.55,
        lng: 78.4694,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Chippili',
    }),
    withCompatFields({
        name: 'Kasiraopeta',
        lat: 13.6353,
        lng: 78.5974,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Kasiraopeta',
    }),
    withCompatFields({
        name: 'Kollabylu',
        lat: 13.5799,
        lng: 78.4976,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Kollabylu',
    }),
    withCompatFields({
        name: 'Kothavaripalle',
        lat: 13.546,
        lng: 78.52,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Kothavaripalle',
    }),
    withCompatFields({
        name: 'Malepadu',
        lat: 13.55,
        lng: 78.5,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Malepadu',
    }),
    withCompatFields({
        name: 'Molakaladinne',
        lat: 13.5332,
        lng: 78.5481,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Molakaladinne',
    }),
    withCompatFields({
        name: 'Pamaiahgaripalle',
        lat: 13.542,
        lng: 78.492,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Pamaiahgaripalle',
    }),
    withCompatFields({
        name: 'Pappireddipalle',
        lat: 13.552,
        lng: 78.489,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Pappireddipalle',
    }),
    withCompatFields({
        name: 'Penchupadu',
        lat: 13.4746,
        lng: 78.457,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Penchupadu',
    }),
    withCompatFields({
        name: 'Ponnetipalem',
        lat: 13.5693,
        lng: 78.4604,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Ponnetipalem',
    }),
    withCompatFields({
        name: 'Pothapalu',
        lat: 13.5954,
        lng: 78.5527,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Pothapalu',
    }),
    withCompatFields({
        name: 'Theneegalavaripalle',
        lat: 13.4717,
        lng: 78.397,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Theneegalavaripalle',
    }),
    withCompatFields({
        name: 'Valasapalle',
        lat: 13.5104,
        lng: 78.4679,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Valasapalle',
    }),
    withCompatFields({
        name: 'Vempalle',
        lat: 13.55,
        lng: 78.5,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Vempalle',
    }),
    withCompatFields({
        name: 'Venkappakota',
        lat: 13.5778,
        lng: 78.532,
        zone: ZONE.RURAL,
        mandal: 'Madanapalle',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Venkappakota',
    }),
    withCompatFields({
        name: 'Achanta',
        lat: 16.6028,
        lng: 81.8067,
        zone: ZONE.RURAL,
        mandal: 'Achanta',
        district: 'West Godavari',
        lgdCode: 4981,
        aliases: ['Achanta Mandal'],
    }),
    withCompatFields({
        name: 'Addanki',
        lat: 15.8123,
        lng: 79.9721,
        zone: ZONE.RURAL,
        mandal: 'Addanki',
        district: 'Prakasam',
        lgdCode: 5112,
        aliases: ['Addanki Mandal'],
    }),
    withCompatFields({
        name: 'Addateegala',
        lat: 17.5123,
        lng: 82.5123,
        zone: ZONE.TRIBAL,
        mandal: 'Addateegala',
        district: 'Polavaram',
        lgdCode: 4887,
        aliases: ['Addatigala'],
    }),
    withCompatFields({
        name: 'Visakhapatnam',
        lat: 17.6868,
        lng: 83.2185,
        zone: ZONE.URBAN,
        mandal: 'Visakhapatnam',
        district: 'Visakhapatnam',
        lgdCode: 520,
        panchayat: 'Visakhapatnam',
    }),
    withCompatFields({
        name: 'Tirupati',
        lat: 13.6288,
        lng: 79.4192,
        zone: ZONE.URBAN,
        mandal: 'Tirupati',
        district: 'Tirupati',
        lgdCode: 752,
        panchayat: 'Tirupati',
    }),
    withCompatFields({
        name: 'Kurnool',
        lat: 15.8281,
        lng: 78.0373,
        zone: ZONE.URBAN,
        mandal: 'Kurnool',
        district: 'Kurnool',
        lgdCode: 511,
        panchayat: 'Kurnool',
    }),
]);

const EXPANDED_AP_LOCATIONS = Object.freeze([
    withCompatFields({
        name: 'Anandapuram',
        lat: 17.6809,
        lng: 83.0852,
        zone: ZONE.RURAL,
        mandal: 'Anandapuram',
        district: 'Visakhapatnam',
        lgdCode: 4863,
        panchayat: 'Anandapuram',
    }),
    withCompatFields({
        name: 'Bheemunipatnam',
        aliases: ['Bhimunipatnam', 'Bheemunipatnam'],
        lat: 17.8902,
        lng: 83.452,
        zone: ZONE.COASTAL,
        mandal: 'Bheemunipatnam',
        district: 'Visakhapatnam',
        lgdCode: 4865,
        panchayat: 'Bheemunipatnam',
    }),
    withCompatFields({
        name: 'Chodavaram',
        lat: 17.6801,
        lng: 83.2016,
        zone: ZONE.RURAL,
        mandal: 'Chodavaram',
        district: 'Visakhapatnam',
        lgdCode: 4863,
        panchayat: 'Chodavaram',
    }),
    withCompatFields({
        name: 'Sabbavaram',
        lat: 17.6809,
        lng: 83.0852,
        zone: ZONE.RURAL,
        mandal: 'Sabbavaram',
        district: 'Visakhapatnam',
        lgdCode: 4863,
        panchayat: 'Sabbavaram',
    }),
    withCompatFields({
        name: 'Bobbili',
        lat: 18.573,
        lng: 83.4167,
        zone: ZONE.RURAL,
        mandal: 'Bobbili',
        district: 'Vizianagaram',
        lgdCode: 4816,
        panchayat: 'Bobbili',
    }),
    withCompatFields({
        name: 'Cheepurupalli',
        lat: 18.3,
        lng: 83.5667,
        zone: ZONE.RURAL,
        mandal: 'Cheepurupalli',
        district: 'Vizianagaram',
        lgdCode: 4827,
        panchayat: 'Cheepurupalli',
    }),
    withCompatFields({
        name: 'Gajapathinagaram',
        lat: 18.3,
        lng: 83.55,
        zone: ZONE.RURAL,
        mandal: 'Gajapathinagaram',
        district: 'Vizianagaram',
        lgdCode: 4815,
        panchayat: 'Gajapathinagaram',
    }),
    withCompatFields({
        name: 'Avilala',
        lat: 13.6355,
        lng: 79.4199,
        zone: ZONE.RURAL,
        mandal: 'Tirupati Rural',
        district: 'Tirupati',
        lgdCode: 595740,
        panchayat: 'Avilala',
    }),
    withCompatFields({
        name: 'Brahmana Pattu',
        aliases: ['Brahmanapattu'],
        lat: 13.6288,
        lng: 79.4192,
        zone: ZONE.RURAL,
        mandal: 'Tirupati Rural',
        district: 'Tirupati',
        lgdCode: 595737,
        panchayat: 'Brahmana Pattu',
    }),
    withCompatFields({
        name: 'Cherlopalle',
        lat: 13.6355,
        lng: 79.4199,
        zone: ZONE.RURAL,
        mandal: 'Tirupati Rural',
        district: 'Tirupati',
        lgdCode: 595738,
        panchayat: 'Cherlopalle',
    }),
    withCompatFields({
        name: 'Amaravathi',
        aliases: ['Amaravati'],
        lat: 16.5735,
        lng: 80.3567,
        zone: ZONE.RURAL,
        mandal: 'Amaravathi',
        district: 'Guntur',
        lgdCode: 5052,
        panchayat: 'Amaravathi',
    }),
    withCompatFields({
        name: 'Amarthalur',
        lat: 16.0733,
        lng: 80.665,
        zone: ZONE.RURAL,
        mandal: 'Amarthalur',
        district: 'Guntur',
        lgdCode: 5086,
        panchayat: 'Amarthalur',
    }),
    withCompatFields({
        name: 'Atchampet',
        lat: 16.3736,
        lng: 80.005,
        zone: ZONE.RURAL,
        mandal: 'Atchampet',
        district: 'Guntur',
        lgdCode: 5050,
        panchayat: 'Atchampet',
    }),
    withCompatFields({
        name: 'Amalapuram',
        lat: 16.5735,
        lng: 82.0167,
        zone: ZONE.COASTAL,
        mandal: 'Amalapuram',
        district: 'Dr. B.R. Ambedkar Konaseema',
        lgdCode: 747,
        panchayat: 'Amalapuram',
    }),
    withCompatFields({
        name: 'Ainavilli',
        lat: 16.65,
        lng: 82,
        zone: ZONE.RURAL,
        mandal: 'Ainavilli',
        district: 'Dr. B.R. Ambedkar Konaseema',
        lgdCode: 747,
        panchayat: 'Ainavilli',
    }),
    withCompatFields({
        name: 'Allavaram',
        lat: 16.6,
        lng: 82.05,
        zone: ZONE.COASTAL,
        mandal: 'Allavaram',
        district: 'Dr. B.R. Ambedkar Konaseema',
        lgdCode: 747,
        panchayat: 'Allavaram',
    }),
    withCompatFields({
        name: 'Ambajipeta',
        lat: 16.55,
        lng: 82,
        zone: ZONE.RURAL,
        mandal: 'Ambajipeta',
        district: 'Dr. B.R. Ambedkar Konaseema',
        lgdCode: 747,
        panchayat: 'Ambajipeta',
    }),
    withCompatFields({
        name: 'Atreyapuram',
        lat: 16.62,
        lng: 81.95,
        zone: ZONE.RURAL,
        mandal: 'Atreyapuram',
        district: 'Dr. B.R. Ambedkar Konaseema',
        lgdCode: 747,
        panchayat: 'Atreyapuram',
    }),
    withCompatFields({
        name: 'Rajahmundry',
        aliases: ['Rajamahendravaram'],
        lat: 17.005,
        lng: 81.7799,
        zone: ZONE.URBAN,
        mandal: 'Rajahmundry',
        district: 'East Godavari',
        lgdCode: 505,
        panchayat: 'Rajahmundry',
    }),
    withCompatFields({
        name: 'Anaparthi',
        lat: 16.95,
        lng: 82,
        zone: ZONE.RURAL,
        mandal: 'Anaparthi',
        district: 'East Godavari',
        lgdCode: 505,
        panchayat: 'Anaparthi',
    }),
    withCompatFields({
        name: 'Biccavolu',
        lat: 16.95,
        lng: 82.05,
        zone: ZONE.RURAL,
        mandal: 'Biccavolu',
        district: 'East Godavari',
        lgdCode: 505,
        panchayat: 'Biccavolu',
    }),
    withCompatFields({
        name: 'Chagallu',
        lat: 17,
        lng: 81.95,
        zone: ZONE.RURAL,
        mandal: 'Chagallu',
        district: 'East Godavari',
        lgdCode: 505,
        panchayat: 'Chagallu',
    }),
    withCompatFields({
        name: 'Eluru',
        lat: 16.7138,
        lng: 81.0933,
        zone: ZONE.URBAN,
        mandal: 'Eluru',
        district: 'Eluru',
        lgdCode: 748,
        panchayat: 'Eluru',
    }),
    withCompatFields({
        name: 'Agiripalli',
        lat: 16.65,
        lng: 81.05,
        zone: ZONE.RURAL,
        mandal: 'Agiripalli',
        district: 'Eluru',
        lgdCode: 748,
        panchayat: 'Agiripalli',
    }),
    withCompatFields({
        name: 'Bheemadole',
        lat: 16.7,
        lng: 81.1,
        zone: ZONE.RURAL,
        mandal: 'Bheemadole',
        district: 'Eluru',
        lgdCode: 748,
        panchayat: 'Bheemadole',
    }),
    withCompatFields({
        name: 'Buttayagudem',
        lat: 17.1,
        lng: 81.2,
        zone: ZONE.RURAL,
        mandal: 'Buttayagudem',
        district: 'Eluru',
        lgdCode: 748,
        panchayat: 'Buttayagudem',
    }),
    withCompatFields({
        name: 'Kakinada',
        lat: 16.9891,
        lng: 82.2475,
        zone: ZONE.URBAN,
        mandal: 'Kakinada',
        district: 'Kakinada',
        lgdCode: 746,
        panchayat: 'Kakinada',
    }),
    withCompatFields({
        name: 'Kakinada Rural',
        lat: 16.95,
        lng: 82.25,
        zone: ZONE.COASTAL,
        mandal: 'Kakinada Rural',
        district: 'Kakinada',
        lgdCode: 746,
        panchayat: 'Kakinada Rural',
    }),
    withCompatFields({
        name: 'Peddapuram',
        lat: 17.08,
        lng: 82.15,
        zone: ZONE.RURAL,
        mandal: 'Peddapuram',
        district: 'Kakinada',
        lgdCode: 746,
        panchayat: 'Peddapuram',
    }),
    withCompatFields({
        name: 'Machilipatnam',
        lat: 16.187,
        lng: 81.138,
        zone: ZONE.COASTAL,
        mandal: 'Machilipatnam',
        district: 'Krishna',
        lgdCode: 510,
        panchayat: 'Machilipatnam',
    }),
    withCompatFields({
        name: 'Avanigadda',
        lat: 16.02,
        lng: 80.92,
        zone: ZONE.COASTAL,
        mandal: 'Avanigadda',
        district: 'Krishna',
        lgdCode: 510,
        panchayat: 'Avanigadda',
    }),
    withCompatFields({
        name: 'Bantumilli',
        lat: 16.35,
        lng: 81,
        zone: ZONE.RURAL,
        mandal: 'Bantumilli',
        district: 'Krishna',
        lgdCode: 510,
        panchayat: 'Bantumilli',
    }),
    withCompatFields({
        name: 'Challapalli',
        lat: 16.12,
        lng: 80.92,
        zone: ZONE.RURAL,
        mandal: 'Challapalli',
        district: 'Krishna',
        lgdCode: 510,
        panchayat: 'Challapalli',
    }),
    withCompatFields({
        name: 'Adoni',
        lat: 15.675,
        lng: 77.275,
        zone: ZONE.URBAN,
        mandal: 'Adoni',
        district: 'Kurnool',
        lgdCode: 511,
        panchayat: 'Adoni',
    }),
    withCompatFields({
        name: 'Alur',
        lat: 15.4,
        lng: 77.5,
        zone: ZONE.RURAL,
        mandal: 'Alur',
        district: 'Kurnool',
        lgdCode: 511,
        panchayat: 'Alur',
    }),
    withCompatFields({
        name: 'Aspari',
        lat: 15.55,
        lng: 77.4,
        zone: ZONE.RURAL,
        mandal: 'Aspari',
        district: 'Kurnool',
        lgdCode: 511,
        panchayat: 'Aspari',
    }),
    withCompatFields({
        name: 'Markapuram',
        lat: 15.736,
        lng: 79.267,
        zone: ZONE.RURAL,
        mandal: 'Markapuram',
        district: 'Markapuram',
        lgdCode: 790,
        panchayat: 'Markapuram',
    }),
    withCompatFields({
        name: 'Ardhaveedu',
        lat: 15.65,
        lng: 79.1,
        zone: ZONE.RURAL,
        mandal: 'Ardhaveedu',
        district: 'Markapuram',
        lgdCode: 790,
        panchayat: 'Ardhaveedu',
    }),
    withCompatFields({
        name: 'Bestavaripeta',
        lat: 15.55,
        lng: 79.15,
        zone: ZONE.RURAL,
        mandal: 'Bestavaripeta',
        district: 'Markapuram',
        lgdCode: 790,
        panchayat: 'Bestavaripeta',
    }),
    withCompatFields({
        name: 'Chandra Sekhara Puram',
        aliases: ['C.S. Puram', 'Chandra Sekharapuram'],
        lat: 15.45,
        lng: 79.2,
        zone: ZONE.RURAL,
        mandal: 'Chandra Sekhara Puram',
        district: 'Markapuram',
        lgdCode: 790,
        panchayat: 'Chandra Sekhara Puram',
    }),
    withCompatFields({
        name: 'Nandyal',
        lat: 15.478,
        lng: 78.483,
        zone: ZONE.URBAN,
        mandal: 'Nandyal',
        district: 'Nandyal',
        lgdCode: 755,
        panchayat: 'Nandyal',
    }),
    withCompatFields({
        name: 'Allagadda',
        lat: 15.85,
        lng: 78.55,
        zone: ZONE.RURAL,
        mandal: 'Allagadda',
        district: 'Nandyal',
        lgdCode: 755,
        panchayat: 'Allagadda',
    }),
    withCompatFields({
        name: 'Atmakur',
        lat: 15.88,
        lng: 78.58,
        zone: ZONE.RURAL,
        mandal: 'Atmakur',
        district: 'Nandyal',
        lgdCode: 755,
        panchayat: 'Atmakur',
    }),
    withCompatFields({
        name: 'Banaganapalli',
        lat: 15.48,
        lng: 78.22,
        zone: ZONE.RURAL,
        mandal: 'Banaganapalli',
        district: 'Nandyal',
        lgdCode: 755,
        panchayat: 'Banaganapalli',
    }),
    withCompatFields({
        name: 'Bethamcherla',
        lat: 15.45,
        lng: 78.15,
        zone: ZONE.RURAL,
        mandal: 'Bethamcherla',
        district: 'Nandyal',
        lgdCode: 755,
        panchayat: 'Bethamcherla',
    }),
    withCompatFields({
        name: 'Vijayawada',
        lat: 16.5062,
        lng: 80.648,
        zone: ZONE.URBAN,
        mandal: 'Vijayawada',
        district: 'NTR',
        lgdCode: 749,
        panchayat: 'Vijayawada',
    }),
    withCompatFields({
        name: 'Atlapragada Konduru',
        lat: 16.55,
        lng: 80.7,
        zone: ZONE.RURAL,
        mandal: 'Atlapragada Konduru',
        district: 'NTR',
        lgdCode: 749,
        panchayat: 'Atlapragada Konduru',
    }),
    withCompatFields({
        name: 'Chandarlapadu',
        lat: 16.6,
        lng: 80.65,
        zone: ZONE.RURAL,
        mandal: 'Chandarlapadu',
        district: 'NTR',
        lgdCode: 749,
        panchayat: 'Chandarlapadu',
    }),
    withCompatFields({
        name: 'Narasaraopet',
        lat: 16.236,
        lng: 80.0542,
        zone: ZONE.URBAN,
        mandal: 'Narasaraopet',
        district: 'Palnadu',
        lgdCode: 751,
        panchayat: 'Narasaraopet',
    }),
    withCompatFields({
        name: 'Amaravathi',
        aliases: ['Amaravati'],
        lat: 16.5735,
        lng: 80.3567,
        zone: ZONE.RURAL,
        mandal: 'Amaravathi',
        district: 'Palnadu',
        lgdCode: 751,
        panchayat: 'Amaravathi',
    }),
    withCompatFields({
        name: 'Atchampet',
        lat: 16.3736,
        lng: 80.005,
        zone: ZONE.RURAL,
        mandal: 'Atchampet',
        district: 'Palnadu',
        lgdCode: 751,
        panchayat: 'Atchampet',
    }),
    withCompatFields({
        name: 'Parvathipuram',
        lat: 18.7817,
        lng: 83.4268,
        zone: ZONE.RURAL,
        mandal: 'Parvathipuram',
        district: 'Parvathipuram Manyam',
        lgdCode: 743,
        panchayat: 'Parvathipuram',
    }),
    withCompatFields({
        name: 'Balijipeta',
        lat: 18.5,
        lng: 83.5,
        zone: ZONE.RURAL,
        mandal: 'Balijipeta',
        district: 'Parvathipuram Manyam',
        lgdCode: 743,
        panchayat: 'Balijipeta',
    }),
    withCompatFields({
        name: 'Bhamini',
        lat: 18.4,
        lng: 83.45,
        zone: ZONE.RURAL,
        mandal: 'Bhamini',
        district: 'Parvathipuram Manyam',
        lgdCode: 743,
        panchayat: 'Bhamini',
    }),
    withCompatFields({
        name: 'Polavaram',
        lat: 17.2475,
        lng: 81.6437,
        zone: ZONE.TRIBAL,
        mandal: 'Polavaram',
        district: 'Polavaram',
        lgdCode: 791,
        panchayat: 'Polavaram',
    }),
    withCompatFields({
        name: 'Addateegala',
        aliases: ['Addatigala'],
        lat: 17.5123,
        lng: 82.5123,
        zone: ZONE.TRIBAL,
        mandal: 'Addateegala',
        district: 'Alluri Sitharama Raju',
        lgdCode: 745,
        panchayat: 'Addateegala',
    }),
    withCompatFields({
        name: 'Ongole',
        lat: 15.5029,
        lng: 80.0444,
        zone: ZONE.URBAN,
        mandal: 'Ongole',
        district: 'Prakasam',
        lgdCode: 517,
        panchayat: 'Ongole',
    }),
    withCompatFields({
        name: 'Chirala',
        lat: 15.827,
        lng: 80.352,
        zone: ZONE.COASTAL,
        mandal: 'Chirala',
        district: 'Prakasam',
        lgdCode: 517,
        panchayat: 'Chirala',
    }),
    withCompatFields({
        name: 'Srikakulam',
        lat: 18.2967,
        lng: 83.8978,
        zone: ZONE.URBAN,
        mandal: 'Srikakulam',
        district: 'Srikakulam',
        lgdCode: 519,
        panchayat: 'Srikakulam',
    }),
    withCompatFields({
        name: 'Amadalavalasa',
        lat: 18.25,
        lng: 83.9,
        zone: ZONE.RURAL,
        mandal: 'Amadalavalasa',
        district: 'Srikakulam',
        lgdCode: 519,
        panchayat: 'Amadalavalasa',
    }),
    withCompatFields({
        name: 'Burja',
        lat: 18.3,
        lng: 83.85,
        zone: ZONE.RURAL,
        mandal: 'Burja',
        district: 'Srikakulam',
        lgdCode: 519,
        panchayat: 'Burja',
    }),
    withCompatFields({
        name: 'Nellore',
        lat: 14.4426,
        lng: 79.9865,
        zone: ZONE.URBAN,
        mandal: 'Nellore',
        district: 'Sri Potti Sriramulu Nellore',
        lgdCode: 515,
        panchayat: 'Nellore',
    }),
    withCompatFields({
        name: 'Allur',
        lat: 14.45,
        lng: 80,
        zone: ZONE.RURAL,
        mandal: 'Allur',
        district: 'Sri Potti Sriramulu Nellore',
        lgdCode: 515,
        panchayat: 'Allur',
    }),
    withCompatFields({
        name: 'Anumasamudrampeta',
        lat: 14.4,
        lng: 79.95,
        zone: ZONE.RURAL,
        mandal: 'Anumasamudrampeta',
        district: 'Sri Potti Sriramulu Nellore',
        lgdCode: 515,
        panchayat: 'Anumasamudrampeta',
    }),
    withCompatFields({
        name: 'Puttaparthi',
        lat: 14.165,
        lng: 77.813,
        zone: ZONE.RURAL,
        mandal: 'Puttaparthi',
        district: 'Sri Sathya Sai',
        lgdCode: 754,
        panchayat: 'Puttaparthi',
    }),
    withCompatFields({
        name: 'Hindupur',
        lat: 13.829,
        lng: 77.491,
        zone: ZONE.RURAL,
        mandal: 'Hindupur',
        district: 'Sri Sathya Sai',
        lgdCode: 754,
        panchayat: 'Hindupur',
    }),
    withCompatFields({
        name: 'Agali',
        lat: 13.85,
        lng: 77.55,
        zone: ZONE.RURAL,
        mandal: 'Agali',
        district: 'Sri Sathya Sai',
        lgdCode: 754,
        panchayat: 'Agali',
    }),
    withCompatFields({
        name: 'Eluru',
        lat: 16.7138,
        lng: 81.0933,
        zone: ZONE.URBAN,
        mandal: 'Eluru',
        district: 'West Godavari',
        lgdCode: 523,
        panchayat: 'Eluru',
    }),
    withCompatFields({
        name: 'Bhimavaram',
        lat: 16.5443,
        lng: 81.5212,
        zone: ZONE.URBAN,
        mandal: 'Bhimavaram',
        district: 'West Godavari',
        lgdCode: 523,
        panchayat: 'Bhimavaram',
    }),
    withCompatFields({
        name: 'Akividu',
        lat: 16.58,
        lng: 81.38,
        zone: ZONE.RURAL,
        mandal: 'Akividu',
        district: 'West Godavari',
        lgdCode: 523,
        panchayat: 'Akividu',
    }),
    withCompatFields({
        name: 'Attili',
        lat: 16.6,
        lng: 81.4,
        zone: ZONE.RURAL,
        mandal: 'Attili',
        district: 'West Godavari',
        lgdCode: 523,
        panchayat: 'Attili',
    }),
    withCompatFields({
        name: 'Kadapa',
        aliases: ['Cuddapah'],
        lat: 14.4674,
        lng: 78.8241,
        zone: ZONE.URBAN,
        mandal: 'Kadapa',
        district: 'Y.S.R. Kadapa',
        lgdCode: 504,
        panchayat: 'Kadapa',
    }),
    withCompatFields({
        name: 'Badvel',
        lat: 14.45,
        lng: 79.05,
        zone: ZONE.RURAL,
        mandal: 'Badvel',
        district: 'Y.S.R. Kadapa',
        lgdCode: 504,
        panchayat: 'Badvel',
    }),
    withCompatFields({
        name: 'Atlur',
        lat: 14.5,
        lng: 78.9,
        zone: ZONE.RURAL,
        mandal: 'Atlur',
        district: 'Y.S.R. Kadapa',
        lgdCode: 504,
        panchayat: 'Atlur',
    }),
    withCompatFields({
        name: 'Chapad',
        lat: 14.4,
        lng: 78.85,
        zone: ZONE.RURAL,
        mandal: 'Chapad',
        district: 'Y.S.R. Kadapa',
        lgdCode: 504,
        panchayat: 'Chapad',
    }),
    withCompatFields({
        name: 'Anakapalli',
        lat: 17.6809,
        lng: 83.0852,
        zone: ZONE.URBAN,
        mandal: 'Anakapalli',
        district: 'Anakapalli',
        lgdCode: 744,
        panchayat: 'Anakapalli',
    }),
    withCompatFields({
        name: 'Atchuthapuram',
        aliases: ['Achutapuram'],
        lat: 17.68,
        lng: 83,
        zone: ZONE.RURAL,
        mandal: 'Atchuthapuram',
        district: 'Anakapalli',
        lgdCode: 744,
        panchayat: 'Atchuthapuram',
    }),
    withCompatFields({
        name: 'Butchayyapeta',
        lat: 17.65,
        lng: 83.05,
        zone: ZONE.RURAL,
        mandal: 'Butchayyapeta',
        district: 'Anakapalli',
        lgdCode: 744,
        panchayat: 'Butchayyapeta',
    }),
    withCompatFields({
        name: 'Cheedikada',
        lat: 17.62,
        lng: 83.12,
        zone: ZONE.RURAL,
        mandal: 'Cheedikada',
        district: 'Anakapalli',
        lgdCode: 744,
        panchayat: 'Cheedikada',
    }),
    withCompatFields({
        name: 'Anandapuram',
        lat: 17.6809,
        lng: 83.0852,
        zone: ZONE.RURAL,
        mandal: 'Anandapuram',
        district: 'Anakapalli',
        lgdCode: 744,
        panchayat: 'Anandapuram',
    }),
    withCompatFields({
        name: 'Bheemunipatnam',
        aliases: ['Bhimunipatnam', 'Bheemunipatnam'],
        lat: 17.8902,
        lng: 83.452,
        zone: ZONE.COASTAL,
        mandal: 'Bheemunipatnam',
        district: 'Anakapalli',
        lgdCode: 744,
        panchayat: 'Bheemunipatnam',
    }),
    withCompatFields({
        name: 'Araku Valley',
        lat: 18.33,
        lng: 82.88,
        zone: ZONE.TRIBAL,
        mandal: 'Araku Valley',
        district: 'Alluri Sitharama Raju',
        lgdCode: 745,
        panchayat: 'Araku Valley',
    }),
    withCompatFields({
        name: 'Paderu',
        lat: 18.08,
        lng: 82.67,
        zone: ZONE.TRIBAL,
        mandal: 'Paderu',
        district: 'Alluri Sitharama Raju',
        lgdCode: 745,
        panchayat: 'Paderu',
    }),
    withCompatFields({
        name: 'Anantnagiri',
        lat: 17.68,
        lng: 82.95,
        zone: ZONE.TRIBAL,
        mandal: 'Anantnagiri',
        district: 'Alluri Sitharama Raju',
        lgdCode: 745,
        panchayat: 'Anantnagiri',
    }),
    withCompatFields({
        name: 'Anantapur',
        aliases: ['Anantapur Urban'],
        lat: 14.6834,
        lng: 77.5997,
        zone: ZONE.URBAN,
        mandal: 'Anantapur Urban',
        district: 'Ananthapuramu',
        lgdCode: 502,
        panchayat: 'Anantapur',
    }),
    withCompatFields({
        name: 'Hindupur',
        lat: 13.829,
        lng: 77.491,
        zone: ZONE.RURAL,
        mandal: 'Hindupur',
        district: 'Ananthapuramu',
        lgdCode: 502,
        panchayat: 'Hindupur',
    }),
    withCompatFields({
        name: 'Bukkapatnam',
        lat: 14.5,
        lng: 77.8,
        zone: ZONE.RURAL,
        mandal: 'Bukkapatnam',
        district: 'Ananthapuramu',
        lgdCode: 502,
        panchayat: 'Bukkapatnam',
    }),
    withCompatFields({
        name: 'Bathalapalli',
        lat: 14.55,
        lng: 77.75,
        zone: ZONE.RURAL,
        mandal: 'Bathalapalli',
        district: 'Ananthapuramu',
        lgdCode: 502,
        panchayat: 'Bathalapalli',
    }),
    withCompatFields({
        name: 'Rayachoti',
        lat: 14.05,
        lng: 78.75,
        zone: ZONE.SEMIURBAN,
        mandal: 'Rayachoti',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Rayachoti',
    }),
    withCompatFields({
        name: 'Rajampet',
        lat: 14.18,
        lng: 79.16,
        zone: ZONE.RURAL,
        mandal: 'Rajampet',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Rajampet',
    }),
    withCompatFields({
        name: 'Puttaparthi',
        lat: 14.165,
        lng: 77.813,
        zone: ZONE.RURAL,
        mandal: 'Puttaparthi',
        district: 'Annamayya',
        lgdCode: 753,
        panchayat: 'Puttaparthi',
    }),
    withCompatFields({
        name: 'Bapatla',
        lat: 15.904,
        lng: 80.464,
        zone: ZONE.COASTAL,
        mandal: 'Bapatla',
        district: 'Bapatla',
        lgdCode: 750,
        panchayat: 'Bapatla',
    }),
    withCompatFields({
        name: 'Chirala',
        lat: 15.827,
        lng: 80.352,
        zone: ZONE.COASTAL,
        mandal: 'Chirala',
        district: 'Bapatla',
        lgdCode: 750,
        panchayat: 'Chirala',
    }),
    withCompatFields({
        name: 'Amarthalur',
        lat: 16.0733,
        lng: 80.665,
        zone: ZONE.RURAL,
        mandal: 'Amarthalur',
        district: 'Bapatla',
        lgdCode: 750,
        panchayat: 'Amarthalur',
    }),
    withCompatFields({
        name: 'Bhattiprolu',
        lat: 16.1,
        lng: 80.78,
        zone: ZONE.COASTAL,
        mandal: 'Bhattiprolu',
        district: 'Bapatla',
        lgdCode: 750,
        panchayat: 'Bhattiprolu',
    }),
    withCompatFields({
        name: 'Chittoor',
        lat: 13.216,
        lng: 79.099,
        zone: ZONE.URBAN,
        mandal: 'Chittoor',
        district: 'Chittoor',
        lgdCode: 503,
        panchayat: 'Chittoor',
    }),
    withCompatFields({
        name: 'Baireddipalle',
        lat: 13.65,
        lng: 78.85,
        zone: ZONE.RURAL,
        mandal: 'Baireddipalle',
        district: 'Chittoor',
        lgdCode: 503,
        panchayat: 'Baireddipalle',
    }),
    withCompatFields({
        name: 'Bangarupalem',
        lat: 13.7,
        lng: 78.9,
        zone: ZONE.RURAL,
        mandal: 'Bangarupalem',
        district: 'Chittoor',
        lgdCode: 503,
        panchayat: 'Bangarupalem',
    }),
    withCompatFields({
        name: 'Kuppam',
        lat: 12.78,
        lng: 78.35,
        zone: ZONE.RURAL,
        mandal: 'Kuppam',
        district: 'Chittoor',
        lgdCode: 503,
        panchayat: 'Kuppam',
    }),
]);

const AP_LOCATIONS = Object.freeze([
    ...BASE_AP_LOCATIONS,
    ...EXPANDED_AP_LOCATIONS,
]);

const AP_JOB_CATEGORIES = Object.freeze({
    DIGITAL_GIG: Object.freeze(['delivery', 'field_sales', 'promoter', 'video_verification', 'on_ground_support']),
    AGRICULTURE: Object.freeze(['agriculture', 'harvest', 'farm_support', 'tractor', 'sorting']),
    VOICE: Object.freeze(['telecalling', 'support', 'sales_calling', 'voice_process']),
    INFRA: Object.freeze(['infra', 'construction_support', 'vbg', 'rural_work']),
});

const AP_ADJACENCY_GRAPH = new Map([
    ['madanapalle', new Set(['annamayya', 'chittoor', 'tirupati'])],
    ['annamayya', new Set(['madanapalle', 'chittoor', 'y s r kadapa'])],
    ['tirupati', new Set(['chittoor', 'annamayya'])],
    ['visakhapatnam', new Set(['anakapalli', 'alluri sitharama raju'])],
]);

const AP_HAVERSINE = Object.freeze({
    PANCHAYAT_KM: 3,
    MANDAL_KM: 12,
    DISTRICT_KM: 90,
    REGIONAL_KM: 250,
});

const VBG_RAM_G_CONFIG = Object.freeze({
    wageActual: 268,
    maxDays: 125,
    pauseMonths: [10, 11, 5, 6],
});

const DIALECT_AFFINITY = Object.freeze({
    rayalaseema: Object.freeze({
        rayalaseema: 1,
        telugu: 0.96,
        coastal: 0.88,
    }),
    coastal: Object.freeze({
        coastal: 1,
        telugu: 0.96,
        rayalaseema: 0.88,
    }),
    telugu: Object.freeze({
        telugu: 1,
        rayalaseema: 0.96,
        coastal: 0.96,
    }),
});

module.exports = {
    ZONE,
    AP_DISTRICTS,
    AP_LOCATIONS,
    AP_JOB_CATEGORIES,
    AP_ADJACENCY_GRAPH,
    AP_HAVERSINE,
    VBG_RAM_G_CONFIG,
    DIALECT_AFFINITY,
};
